const receitas = [
    // {
    //     id: 1,
    //     title: 'Dor de garganta',
    //     imagem: 'https://poupafarma.com.br/wp-content/uploads/2018/04/imagem-6.jpg',
    //     title1:'',
    //     receita1: 'O governo envia três adolescentes de classe operária para Las Encinas, uma das melhores escolas do país. O confronto entre aqueles que têm tudo e aqueles que não têm nada cria uma atmosfera carregada e leva a um assassinato. O mistério é: quem estará por trás do crime?',
    //     title2:'',
    //     // title:'',
    //     // title:'',
    //     // title:'',
    //     // title:'',
    //     // title:'',
    // },
    {
        id: 1,
        title: 'Dor de dente',
        imagem: 'https://images.pexels.com/photos/5624170/pexels-photo-5624170.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        title1:'Água morna e sal ou gelo',
        receita1: 'Enxaguar a boca com água morna é utilizado como um primeiro socorro para melhorar a limpeza da boca, eliminar bactérias e ajudar a tratar uma possível infecção. Segurar uma bolsa de gelo no local da dor, ou colocar uma pedra de gelo na boca, porque o frio diminui a inflamação e alivia a dor.',
        title2:'Cravo-da-índia',
        receita2:'Cravo-da-índia ou óleo essencial de cravo-da-índia. Mastigue os cravos-da-índia sobre o dente  dolorido ou embeba um cotonete ou algodão com óleo de cravo-da-índia e aplique sobre o dente. \n O cravo-da-índia tem propriedades analgésicas e antissépticas, ajudando a a combater infecções e a aliviar a dor e a inflamação.',
        title3:'Hortelã',
        receita3:'Coloque 1 colher (sopa) de folhas picadas de hortelã numa xícara e cubra com água fervente. Tampe e deixe repousar por cerca de 20 minutos. A seguir, coe e beba. Tome de 3 a 4 xícaras deste chá por dia. \n A hortelã tem propriedades calmantes e refrescantes.',
        title4:'Alho',
        receita4:'Apesar de ser muito comum misturar e eficiente aplicar pó de alho com sal e o pedaço de alho puro no dente dolorido, não é recomendado para todos, uma vez que, em alguns casos pode agravar a situação e inflamar a gengiva. Uma dica é ingerir chá de alho e bocejar sobre o dente, pois consumo de alho na forma de temperos, chás, óleos e extratos pode ser muito eficaz na prevenção de doenças orais. Saiba mais nesses links:',
        link: 'https://www.almanaquesos.com/mito-ou-verdade-alho-alivia-dores-de-dente/',
        link2: 'https://www.youtube.com/watch?v=Xvzkgtl3Epg',
        alerta: 'Consulte o dentista assim que possível, uma vez que as receitas apenas amenizam os sintomas e não tratam a doença.',
    
    },
    {
        id: 2,
        title: 'Cólica',
        imagem: 'https://www.gineco.com.br/wp-content/uploads/2014/05/colica.jpg',
        title1:'Chá de lavanda',
        receita1: 'Colocar 5g de folhas de lavanda em 250ml água e deixar ferver. Ou você pode deixar 1/2 colher de chá de botões da planta e deixar em infusão na mesma quantidade de água. Depois coar, deixar esfriar e beber. Outra opção é retirar as folhas da água e esperar ficarem mornas para aplicar sobre a região.',
        title2:'Chá de camomila',
        receita2:'Ferver 200 ml de água e logo após retirar do fogo, acrescentar 1 colher chá de camomila e deixar tampado o recipiente e em infusão por 10 minutos. Coe e tome. Caso queira potencializar o efeito relaxante e calmante da camomila, é bom acrescentar uma colher de gengibre quando a água tiver fervendo e deixar 5 minutos antes de desligar. O gengibre age como anti-inflamatório diminuindo a dor. ',
        title3:'Chá de orégano',
        receita3:'Acrescentar 1 colher de sopa de orégano à 200ml de água fervente e deixar por cerca de 10 minutos. O orégano tem ação analgésica e ainda ajuda a regular o ciclo. ',
        title4:'Chá de erva-cidreira',
        receita4:'Ferva 200 ml de água e logo após desligar acrescente 2 colheres de sopa de folha das planta. Tampe e deixe abafando por cerca de 10 min. Coe e tome morno. A erva-cidreira tem efeito calmante e sedativo.',
        link: '',
        link2: '',
        alerta: 'Uma dica é ingerir cerca de 2 litros de água durante o dia e fazer exercícios físicos mais leves como Yoga. Caso seja um caso mais grave, é indicado procurar um ginecologista que vai prescrever algum tratamento e medicamento específico.',
    },
    {
        id: 3,
        title: 'Dor de cabeça',
        imagem: 'https://images.pexels.com/photos/3812745/pexels-photo-3812745.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        title1:'Chá de boldo',
        receita1: 'Adicionar 2 colheres de chá de folhas de boldo picado em 200mL de água fervente. Deixar descansar por 5 a 10 minutos, coar e tomar morno logo em seguida.',
        title2:'Chá de erva-cidreira',
        receita2:'Ferva 200 ml de água e logo após desligar acrescente 2 colheres de sopa de folha das planta. Tampe e deixe abafando por cerca de 10 min. Coe e tome morno. A erva-cidreira tem efeito calmante e sedativo. Além de ajudar a reduzir o estresse.',
        title3:'Chá de hortelã',
        receita3:'Adicione 300 ml de água, quando começar a ferver desligue o fogo e adicione 20 gramas de folha de hortelã. Tampe o recipiente e deixe a infusão acontecer por aproximadamente 10 minutos. A hortelã possui propriedade analgésica e alivia a tensão',
        title4:'Arruda',
        receita4:' Pegue 1 colher de chá de folhas de arruda e acrescente em 1 xícara de água fervente, deixar por cerca de 15 minutos. Em seguida, coar e beber. Inalar a folhinha e o óleo essencial também é indicado, isto porque ela conta com o óleo essencial que contém undecanona, metilnonilcetona e metilheptilcetona, que possuem propriedades calmantes ao serem aspiradas e aliviam as dores. \n Veja mais benefícios do arruda:',
        link: 'https://www.minhavida.com.br/alimentacao/tudo-sobre/20310-arruda',
        link2: '',
        alerta: 'Se a dor de cabeça for forte ou excessiva e não tenha alívio com rémedio natural, deve-se procurar um médico para saber qual melhor remédio e tratamento para o seu organismo',
    },
    {
        id: 4,
        title: 'Insônia e Ansiedade',
        imagem: 'https://images.pexels.com/photos/3752834/pexels-photo-3752834.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        title1:'Chá de camomila',
        receita1: 'Ferver 200 ml de água e logo após retirar do fogo, acrescentar 1 colher chá de camomila e deixar tampado o recipiente e em infusão por 10 minutos. A camomila contém apigenina, um antioxidante que se liga a certos receptores no cérebro e promove o sono, além de ter efeito calmante.',
        title2:'Chá de erva-cidreira',
        receita2:'Ferva 200 ml de água e logo após desligar acrescente 2 colheres de sopa de folha das planta. Tampe e deixe abafando por cerca de 10 min. Coe e tome morno. A erva-cidreira tem efeito calmante e sedativo e pode ser utilizada em caso de perturbações do sono e nervosismo.',
        title3:'Chá de flor de laranjeira',
        receita3:'Adicione 300 ml de água, quando começar a ferver desligue o fogo e acrescente duas colheres de sopa de flor de laranjeira. Tampe o recipiente e deixe a infusão acontecer por aproximadamente 10 minutos. As substâncias presentes na flor relaxam e acalmam as atividades neurais e é excelente para o combate da enxaqueca e insônia.',
        title4:'Flor de maracujá ou Passiflora',
        receita4:' Ferva 200 ml de água. Ao desligar o fogo, acrescente três colheres de chá de folhas secas de maracujá e abafe por dez minutos. A flor de maracuja tem como principal benefício o alivio dos sintomas de insônia, qualidade do sono, ansiedade, inflamação, hiperatividade, nervosismo, equilíbrio do humor. Caso não possua a flor pode substituir pela folha do maracujá que também tem efeito calmante. \n Veja outras receitas caseiras que aliviam a ansiedade e insônia:',
        link: 'https://www.tuasaude.com/remedio-caseiro-para-ansiedade/',
        link2: '',
        alerta: 'O uso destes remédios nunca deve substituir o tratamento indicado pelo médico, nem a realização de sessões de psicoterapia, especialmente no caso da ansiedade, devendo apenas ser um tratamento complementar para ajudar a controlar a ansiedade por mais tempo e causar um alívio de curto prazo.',
    },
    {
        id: 5,
        title: 'Gripe',
        imagem: 'https://www.portaltvcariri.com.br/wp-content/uploads/2020/05/remedios-caseiros-para-curar-a-gripe.jpg',
        title1:'Chá de gengibre',
        receita1: 'Coloque 2 colheres de sopa de gengibre ralado ou picado a cada 2 xícaras de água. Deixe ferver por 10 minutos. Você pode acrescentar gotas de limão para potencializar o efeito. O gengibre favorece a saída do catarro dos brônquios e dos sinus, e o limão é rico em vitamina C.',
        title2:'Chá de mel e limão ',
        receita2:'Deve-se adicionar 2 colheres de sopa de mel a uma xícara de água fervente, mexer bem até se tornar uma mistura toda igual e depois acrescentar o suco puro de 1 limão. Se preferir, você pode tomar apenas o mel e limão sem a água. A junção ajuda a descongestionar o nariz e a garganta e melhoram a respiração.',
        title3:'Chá de alho',
        receita3:'Outra opção é o chá de alho, cujo preparo é 3 dentes de alhos fervidos em 250ml de água por 8 min. Você pode tomar puro ou acrescentar a mistura da receita anterior de limão e mel. O alho inibe o ciclo viral, liberando o muco a fim de normalizar a temperatura corporal.',
        title4:'Sucos',
        receita4:'Sucos de acerola, laranja e limão, podem ser consumidos misturados ou separadamente, pois são frutas ricas em vitamina C, o que estimula o bom funcionamento das células de defesa do corpo. Se preferir adoce com mel. O suco de mel, limão e maçã também é um ótimo expectorante. Para isso, acrescente no liquidificador 2 maçãs, 1 copo de água e 1/2 limão, depois coe e adoce com mel.',
        link: '',
        link2: '',
        alerta: 'Lembrando que persistindo os sintomas é necessário procurar um hospital, e jamais tomar medicamentos sem indicação médica em período anterior. Beba bastante água para fluidificar as secreções',
    },
    {
        id: 6,
        title: 'Azia e queimação',
        imagem: 'https://coracaoevida.com.br/wp-content/uploads/2017/08/azia-robertokalil.jpg',
        title1:'Chá de boldo',
        receita1: 'Adicionar 2 colheres de chá de folhas de boldo picado em 200mL de água fervente. Deixar descansar por 5 a 10 minutos, coar e tomar morno logo em seguida. Você pode optar por acrescentar uma colher de sopa de dente-de-leão, uma vez que aumenta a produção de bile e favorece a digestão. As propriedades adstringentes do boldo reduzem a acidez do estômago.',
        title2:'Suco de batata crua',
        receita2:'Pode-se conseguir o suco da batata inglesa passando-a pelo processador de alimentos. Outra forma é bater no liquidificador duas unidades descascadas em 180ml de água até virar um suco. A batata é um alimento alcalino e irá retirar a acidez do estômago, eliminando a azia.',
        title3:'Bicarbonato de sódio',
        receita3:'Misture uma colher de café com bicarbonato de sódio em 100 ml de água e beba. Você pode potencializar colocando uma pitada de bicarbonato de sódio no suco de três limões em um copo de 250 ml de água (temperatura ambiente). o limão ainda combate a acidez do estômago e o bicarbonato possui efeito alcalinizante.',
        title4:'',
        receita4:'',
        link: '',
        link2: '',
        alerta: 'Se os sinais e sintomas se tornarem frequentes e persistirem, o melhor é ir ao médico, pode ser um problema mais grave e esses métodos caseiros são utilizados apenas de forma pontual.',
    },
]

export default receitas